In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:
eq_line = torch.tensor([1., 1.])

In [3]:
θ = torch.tensor([0.2, 0.8], requires_grad=True)
optimizer = torch.optim.SGD([θ], lr=0.2)
for i in range(20):
    optimizer.zero_grad()
    output = torch.prod(θ) # = p * q
    output.backward()
    # enforce that θ sums to 1 through projecting gradient on eq_line.
    θ.grad -= eq_line * torch.dot(θ.grad, eq_line) / torch.dot(eq_line, eq_line)
    # decrese lr if we try to step outside allowed area:
    if torch.any(θ - θ.grad * optimizer.param_groups[0]['lr'] < 0):
        optimizer.param_groups[0]['lr'] *= 0.7
    else:
        optimizer.step()
    print(θ)

tensor([0.1400, 0.8600], requires_grad=True)
tensor([0.0680, 0.9320], requires_grad=True)
tensor([0.0680, 0.9320], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0075, 0.9925], requires_grad=True)
tensor([0.0018, 0.9982], requires_grad=True)
tensor([0.0018, 0.9982], requires_grad=True)
tensor([0.0018, 0.9982], requires_grad=True)
tensor([0.0018, 0.9982], requires_grad=True)
tensor([0.0018, 0.9982], requires_grad=True)
tensor([4.6286e-04, 9.9954e-01], requires_grad=True)
tensor([4.6286e-04, 9.9954e-01], requires_grad=True)
tensor([4.6286e-04, 9.9954e-01], requires_grad=True)
tensor([4.6286e-04, 9.9954e-01], requires_grad=True)
